package cmd

var tuiDefaultBindings = map[rune]string{
	'P': "KEY_POWER",
	'h': "KEY_LEFT",
	'j': "KEY_DOWN",
	'k': "KEY_UP",
	'l': "KEY_RIGHT",
	' ': "KEY_PLAY",
	'"': "KEY_PAUSE",
	'p': "KEY_STOP",
	'`': "KEY_PRECH",
	'Q': "KEY_EXIT",
	'0': "KEY_0",
	'1': "KEY_1",
	'2': "KEY_2",
	'3': "KEY_3",
	'4': "KEY_4",
	'5': "KEY_5",
	'6': "KEY_6",
	'7': "KEY_7",
	'8': "KEY_8",
	'9': "KEY_9",
	'-': "KEY_CHDOWN",
	'+': "KEY_CHUP",
	'/': "KEY_VOLDOWN",
	'*': "KEY_VOLUP",
	'm': "KEY_MUTE",
	'M': "KEY_MENU",
	'g': "KEY_GUIDE",
	'i': "KEY_INFO",
	'L': "KEY_CH_LIST",
	'H': "KEY_HOME",
	'R': "KEY_RED",
	'G': "KEY_GREEN",
	'B': "KEY_BLUE",
	'Y': "KEY_YELLOW",
	's': "KEY_SOURCE",
	't': "KEY_TV",
	'd': "KEY_HDMI",
}
